config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments, only: [:new, :create]
  end
  resources :comments, except: [:new, :create]
  resources :tags
  resources :users

  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    # @article = Article.new(
    #   title: params[:article][:title],
    #   body: params[:article][:body])

    # @article = Article.new(params[:article]) # this won't work, we need to use a helper instead, with require and permit, we plug in the return of the helper below

    @article = Article.new(article_params)
    @article.user = current_user
    @article.save
    flash.notice = "Article '#{@article.title}' Created!"
    redirect_to article_path(@article)
  end

  def destroy
    article = Article.find(params[:id])
    flash.notice = "Article '#{article.title}' deleted!"
    article.destroy

    redirect_to action: "index"
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.user = current_user
    @comment.save
    redirect_to article_path(@comment.article)
  end

  # Why did this go into the controller but the articles one went in the helper.
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(user_name: params[:user_name])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to :controller => :articles, :action => :index
    else
    # If user's login doesn't work, send them back to the login form.
      # redirect_to action: "new"
    end
  end

  def destroy
    session[:user_id] = nil
    # redirect_to :controller => :articles, :action => :index
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    tag = Tag.find(params[:id])
    flash.notice = "Tag '#{tag.name}' deleted!"
    tag.destroy

    redirect_to action: "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    @user.save
    flash.notice = "'#{@user.user_name}' account created!"
    session[:user_id] = @user.id
    redirect_to :controller => :articles, action: "index"
  end

  def new
    @user = User.new
  end

  def show
    if current_user.id.to_s == params[:id].to_s
      @user = User.find(params[:id])
    else
      redirect_to :controller => :articles, action: "index"
    end
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
  # ask maurice about mass assignment
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  # def comment_params
  #   params.require(:comment).permit(:author_name, :body)
  # end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.user.user_name %></h4>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>

    </li>
  <% end %>
</ul>

<% if current_user %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>

app/views/articles/new.html.erb
<h1> Create New Article!!!! </h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h2>Author: <%= @article.user.user_name %></h2>

<% if @article.image.exists? %>
  <p><%= image_tag @article.image.url %></p>
<% end %>

<p><%= @article.body %></p>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<% if current_user && current_user.id.to_s == @article.user.id.to_s %>
  <%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}
   %>
  <%= link_to "edit", edit_article_path(@article) %>
<% end %>

<% if current_user %>
  <%= render partial: 'comments/form' %>
<% end %>




<h3>Comments (<%= @article.comments.size %>)</h3>


<!-- This render line will pass each element of that array one at a time into the partial named "comment". Now we need to create the file  -->
<%= render partial: 'articles/comment', collection: @article.comments %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="head-container">
    <h1> Some Random Rails Blog. Let the cyber-bullying begin!! </h1>
  </div>

  <div class="nav-container">
    <ul>
      <li> <%= link_to "Articles", articles_path %> </li>
      <li> <%= link_to "Tags", :controller => :tags, :action => :index %> </li>

      <% if !current_user %>
        <li> <%= link_to "Register", new_user_path, class: "new_user" %></li>
        <li> <%= link_to "Login", '/login' %></li>
      <% else %>
        <li> <%= link_to current_user.user_name, user_path(current_user) %> </li>
        <li> <%= link_to "Logout", '/logout' %></li>
      <% end %>
    </ul>
  </div>

  <div class="main-container">
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </div>

</body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="articles">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for(@user, html: {multipart: true}) do |f| %>
  <ul>
  <% @user.errors.full_messages.each do |user| %>
    <li><%= user %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_area :email %>
  </p>

  <p>
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </p>
  <p>
    <% if @user.image.exists? %>
      <%= image_tag @user.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a Profile Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1> Register to this blog!!!! </h1>
<%= render partial: 'form' %>

app/views/users/show.html.erb
<h1><%= @user.user_name %></h1>

<h2> Created Articles: </h2>

<ul>
  <% @user.articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>